# Generated by Django 4.1.6 on 2023-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mokeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooyeshmokebmodel',
            name='image',
            field=models.ImageField(upload_to='mokeb'),
        ),
    ]
