# Generated by Django 4.1.6 on 2023-03-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0002_rename_postmodel_uploadimagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagemodel',
            name='image',
            field=models.ImageField(upload_to='uploadimage'),
        ),
    ]
