# Generated by Django 4.1.6 on 2023-02-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='name',
            field=models.CharField(default='واحد داده کاوی', max_length=250),
            preserve_default=False,
        ),
    ]
