# Generated by Django 4.1.6 on 2023-02-15 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='name',
            field=models.CharField(default='ادمین', max_length=50),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='text',
            field=models.TextField(default='#ایران_ما'),
        ),
    ]
