# Generated by Django 4.1.6 on 2023-02-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postmodel_date_alter_postmodel_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='like',
            field=models.IntegerField(default=10),
        ),
    ]
