# Generated by Django 4.1.6 on 2023-02-15 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postmodel_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='like',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
