# Generated by Django 4.1.6 on 2023-03-12 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_postmodel_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='MokebModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(upload_to='post')),
                ('text', models.TextField(default='#موکب_کودکانه')),
                ('name', models.CharField(default='ادمین', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
