# Generated by Django 4.1.6 on 2023-03-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_mokebmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MokebModel',
        ),
    ]
